name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  NODE_VERSION: '18.x'
  AZURE_CONTAINER_REGISTRY: acrtatsukonidemov1
  REPOSITORY_NAME: servicebus-receiver
  CONTAINER_APP_NAME: my-container-app-v1
  RESOURCE_GROUP: tatsukoni-test-v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_CONTAINER_DEPLOY }}

      - name: Set container image tag
        id: tag
        run: |
          echo "CONTAINER_IMAGE_TAG=$(date +%Y%m%d%H%M%S)-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_CREDENTIALS_CLIENT_ID }}
          password: ${{ secrets.AZURE_CREDENTIALS_CLIENT_SECRET }}
      - run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.REPOSITORY_NAME }}:${{ steps.tag.outputs.CONTAINER_IMAGE_TAG }} .
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.REPOSITORY_NAME }}:${{ steps.tag.outputs.CONTAINER_IMAGE_TAG }}
